apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stage-hitohub.yaml
  - prod-hitohub.yaml
  - palserver.yaml
  - ark-survival-ascended.yaml
  - ark-discord-bot.yaml
  - openclaw.yaml
