apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-subnet-router
  namespace: argocd
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argoproj/tailscale-subnet-router
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
