apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-image-updater/application.yaml
- argocd/application.yaml
- ark-discord-bot/application.yaml
- ark-survival-ascended/application.yaml
- boxp-home/application.yaml
- calico/application.yaml
- descheduler/application.yaml
- external-secrets-operator/application.yaml
- hitohub/overlays/prod/application.yaml
- hitohub/overlays/stage/application.yaml
- k8s-ecr-token-updater/application.yaml
- k8s/application.yaml
- kubernetes-dashboard/application.yaml
- local-volume-provisioner/application.yaml
- longhorn/application.yaml
- palserver/application.yaml
- prometheus-operator-crd/application.yaml
- prometheus-operator/application.yaml
- loki/application.yaml
- grafana-alloy/application.yaml
- reloader/application.yaml
- tidb-operator/application.yaml
- kube-vip/application.yaml
