apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/boxp/lolice
      targetRevision: main
      ref: lolice
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 0.12.0
      chart: alloy
      helm:
        valueFiles:
          - $lolice/argoproj/grafana-alloy/helm/values.yaml
    - path: argoproj/grafana-alloy
      repoURL: https://github.com/boxp/lolice
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
