apiVersion: v1
kind: Service
metadata:
  name: starrupture
  namespace: starrupture
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.98
  selector:
    app: starrupture
  ports:
  - name: game-udp
    protocol: UDP
    port: 7777
    targetPort: 7777
  - name: game-tcp
    protocol: TCP
    port: 7777
    targetPort: 7777
