apiVersion: v1
kind: ConfigMap
metadata:
  name: sshd-config
  namespace: bastion
data:
  sshd_config: |
    Port 2222
    PermitRootLogin no
    PasswordAuthentication no
    PubkeyAuthentication yes
    AuthorizedKeysFile /etc/authorized_keys/%u
    Subsystem sftp /usr/lib/ssh/sftp-server
